# Generated by Django 5.2.12 on 2026-10-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Çalışan Kodu')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ad Soyad')),
                ('profession', models.CharField(max_length=120, verbose_name='Meslek')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Departman')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
            ],
            options={
                'verbose_name': 'Çalışan',
                'verbose_name_plural': 'Çalışanlar',
                'ordering': ['full_name', 'code'],
            },
        ),
    ]
