# Generated by Django on 2026-10-08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=120, verbose_name="Etiket")),
                ("route", models.CharField(help_text="Django URL adı, örn. 'production:order_list'.", max_length=120, verbose_name="URL adı (route)")),
                ("icon", models.CharField(blank=True, default="▣", help_text="Kart üzerinde gösterilecek tek karakterlik simge.", max_length=8, verbose_name="İkon")),
                ("group", models.CharField(blank=True, default="ERP Modülleri", help_text="Panelde/menüde hangi başlık altında gösterilecek.", max_length=120, verbose_name="Grup")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("sort_order", models.PositiveIntegerField(default=100, help_text="Küçük değerler önce gösterilir.", verbose_name="Sıra")),
            ],
            options={
                "verbose_name": "Modül Bağlantısı",
                "verbose_name_plural": "Modül Bağlantıları",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
