"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# ONNX Runtime telemetry must be disabled before any embedding-related import.
os.environ["ORT_DISABLE_TELEMETRY"] = "1"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import sentry_sdk
from django.core.exceptions import ImproperlyConfigured
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.django import DjangoIntegration

import environ

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')

OPENAI_API_KEY = env("OPENAI_API_KEY", default="")
OPENAI_MODEL = env("OPENAI_MODEL", default="gpt-4o-mini")

# Deployment workflow supplies this value from the immutable Git commit.
SENTRY_RELEASE = env("SENTRY_RELEASE", default="unknown")

sentry_sdk.init(
    dsn=env("SENTRY_DSN", default=""),
    integrations=[
        DjangoIntegration(),
        CeleryIntegration(),
    ],
    environment=env("SENTRY_ENVIRONMENT", default="production"),
    release=SENTRY_RELEASE,
    send_default_pii=False,
    traces_sample_rate=0.05,          # Performans izleme oranı (düşük kaynak)
    profiles_sample_rate=0.0,         # Profil örnekleme kapalı
    before_send=lambda event, hint: None if env.bool("SENTRY_DISABLED", default=False) else event,
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

DEBUG = env.bool("DJANGO_DEBUG", default=False)
SECRET_KEY = env("DJANGO_SECRET_KEY", default="")
if not SECRET_KEY:
    raise ImproperlyConfigured("DJANGO_SECRET_KEY ortam değişkeni zorunludur.")

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])

# NGINX reverse proxy arkasında CSRF ve host doğrulaması
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_TRUSTED_ORIGINS = env.list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[])
SECURE_SSL_REDIRECT = env.bool("DJANGO_SECURE_SSL_REDIRECT", default=not DEBUG)
# The application is currently served over plain HTTP. Secure cookies must
# remain opt-in until TLS is configured; otherwise browsers discard the CSRF
# cookie and login POST requests fail with HTTP 403.
SECURE_COOKIES = env.bool("DJANGO_SECURE_COOKIES", default=False)
SESSION_COOKIE_SECURE = SECURE_COOKIES
CSRF_COOKIE_SECURE = SECURE_COOKIES
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"
SECURE_HSTS_SECONDS = env.int("DJANGO_SECURE_HSTS_SECONDS", default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "core",
    "inventory",
    "procurement",
    "production",
    "logistics",
    "catalog",
    "quality",
    "distribution",
    "ai",

    "django_celery_beat",
    "django_celery_results",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.SentryModuleTagMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.EnglishResponseTranslationMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB'),
        'USER': env('POSTGRES_USER'),
        'PASSWORD': env('POSTGRES_PASSWORD'),
        'HOST': env('POSTGRES_HOST'),
        'PORT': env('POSTGRES_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "tr"

LANGUAGES = [
    ("tr", "Türkçe"),
    ("en", "English"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
AI_DOCUMENT_MAX_SIZE_BYTES = env.int("AI_DOCUMENT_MAX_SIZE_BYTES", default=10 * 1024 * 1024)
AI_DOCUMENT_TOKEN_ENCODING = env("AI_DOCUMENT_TOKEN_ENCODING", default="cl100k_base")
AI_DOCUMENT_CHUNK_TARGET_TOKENS = env.int("AI_DOCUMENT_CHUNK_TARGET_TOKENS", default=700)
AI_DOCUMENT_CHUNK_MAX_TOKENS = env.int("AI_DOCUMENT_CHUNK_MAX_TOKENS", default=800)
AI_DOCUMENT_CHUNK_OVERLAP_TOKENS = env.int("AI_DOCUMENT_CHUNK_OVERLAP_TOKENS", default=120)
AI_DOCUMENT_EMBEDDING_INPUT_LIMIT_TOKENS = env.int(
    "AI_DOCUMENT_EMBEDDING_INPUT_LIMIT_TOKENS",
    default=8192,
)

AI_EMBEDDING_PROVIDER = env("AI_EMBEDDING_PROVIDER", default="local_fastembed")
AI_EMBEDDING_MODEL_ID = env(
    "AI_EMBEDDING_MODEL_ID", default="intfloat/multilingual-e5-small"
)
AI_EMBEDDING_MODEL_REVISION = env(
    "AI_EMBEDDING_MODEL_REVISION",
    default="614241f622f53c4eeff9890bdc4f31cfecc418b3",
)
AI_EMBEDDING_MODEL_PATH = env(
    "AI_EMBEDDING_MODEL_PATH",
    default="/var/lib/erp/ai-models/intfloat-multilingual-e5-small/614241f622f53c4eeff9890bdc4f31cfecc418b3",
)
AI_EMBEDDING_DIMENSION = env.int("AI_EMBEDDING_DIMENSION", default=384)
AI_EMBEDDING_BATCH_SIZE = env.int("AI_EMBEDDING_BATCH_SIZE", default=4)
AI_EMBEDDING_THREADS = env.int("AI_EMBEDDING_THREADS", default=1)
AI_EMBEDDING_OFFLINE = env.bool("AI_EMBEDDING_OFFLINE", default=True)
AI_EMBEDDING_MAX_MODEL_TOKENS = env.int(
    "AI_EMBEDDING_MAX_MODEL_TOKENS", default=512
)

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f"redis://{env('REDIS_HOST')}:{env('REDIS_PORT')}/1",
    }
}

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="noreply@speeders.com.tr")

ERP_NOTIFICATION_EMAIL = env("ERP_NOTIFICATION_EMAIL", default="teomanunal06@gmail.com")

# Celery Configuration
# https://docs.celeryq.dev/en/stable/userguide/configuration.html

CELERY_BROKER_URL = f"redis://{env('REDIS_HOST')}:{env('REDIS_PORT')}/2"
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

CELERY_TASK_ROUTES = {
    "ai.tasks.process_document": {"queue": "celery"},
    "ai.tasks.embed_document_chunks": {"queue": "embeddings"},
}

# Şirket / Fatura Bilgileri
COMPANY_NAME = env("COMPANY_NAME", default="")
COMPANY_ADDRESS = env("COMPANY_ADDRESS", default="")
COMPANY_TAX_OFFICE = env("COMPANY_TAX_OFFICE", default="")
COMPANY_TAX_NUMBER = env("COMPANY_TAX_NUMBER", default="")
COMPANY_PHONE = env("COMPANY_PHONE", default="")
COMPANY_EMAIL = env("COMPANY_EMAIL", default="")

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="noreply@speeders.com.tr")
ERP_NOTIFICATION_EMAIL = env("ERP_NOTIFICATION_EMAIL", default="")
