# Generated by Django 5.2.12 on 2026-09-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Kuyrukta"),
                    ("uploaded", "Yüklendi"),
                    ("processing", "İşleniyor"),
                    ("ready", "Hazır"),
                    ("failed", "Başarısız"),
                ],
                default="queued",
                editable=False,
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField(verbose_name="Parça Sırası")),
                ("content", models.TextField(verbose_name="İçerik")),
                ("token_count", models.PositiveIntegerField(verbose_name="Token Sayısı")),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Sayfa Numarası",
                    ),
                ),
                (
                    "section_title",
                    models.CharField(blank=True, max_length=255, verbose_name="Bölüm Başlığı"),
                ),
                ("content_hash", models.CharField(max_length=64, verbose_name="İçerik SHA-256")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="ai.document",
                        verbose_name="Doküman",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Doküman Parçası",
                "verbose_name_plural": "AI Doküman Parçaları",
                "ordering": ["document_id", "chunk_index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "chunk_index"),
                        name="uniq_ai_document_chunk_index",
                    ),
                    models.UniqueConstraint(
                        fields=("document", "content_hash"),
                        name="uniq_ai_document_chunk_content_hash",
                    ),
                ],
            },
        ),
    ]
