# Generated by Django 5.2.12 on 2026-09-21 05:21

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_enable_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Embedding Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, editable=False, null=True, verbose_name='Embedding'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_dimensions',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Embedding Boyutu'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_model',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, verbose_name='Embedding Modeli'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_profile_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=64, verbose_name='Embedding Profil SHA-256'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('embedded_at__isnull', True), ('embedding__isnull', True), ('embedding_dimensions__isnull', True), ('embedding_model', ''), ('embedding_profile_hash', '')), models.Q(('embedded_at__isnull', False), ('embedding__isnull', False), ('embedding_dimensions', 384), ('embedding_dimensions__isnull', False), ('embedding_profile_hash__regex', '^[0-9a-f]{64}$'), models.Q(('embedding_model', ''), _negated=True)), _connector='OR'), name='ai_chunk_embedding_complete'),
        ),
    ]
